export const LOAD_DISABLED_LABELED_GOODS = 'LOAD_DISABLED_LABELED_GOODS';
export const LOAD_DISABLED_LABELED_GOODS_SUCCESS =
  'LOAD_DISABLED_LABELED_GOODS_SUCCESS';
export const LOAD_DISABLED_LABELED_GOODS_FAILURE =
  'LOAD_DISABLED_LABELED_GOODS_FAILURE';
export const ENABLE_LABELED_GOODS = 'ENABLE_LABELED_GOODS';
export const ENABLE_LABELED_GOODS_SUCCESS = 'ENABLE_LABELED_GOODS_SUCCESS';
export const ENABLE_LABELED_GOODS_FAILURE = 'ENABLE_LABELED_GOODS_FAILURE';
