//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasladdinPlace.UI.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NasladdinPlace.UI.Resources.Views.Shared._Navigation", typeof(_Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние системы.
        /// </summary>
        internal static string API_State {
            get {
                return ResourceManager.GetString("API State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        internal static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокировка.
        /// </summary>
        internal static string Disabled_labels {
            get {
                return ResourceManager.GetString("Disabled labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидки.
        /// </summary>
        internal static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Движение ТМЦ.
        /// </summary>
        internal static string GoodsMoving {
            get {
                return ResourceManager.GetString("GoodsMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификация.
        /// </summary>
        internal static string Identification_of_goods {
            get {
                return ResourceManager.GetString("Identification of goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производители.
        /// </summary>
        internal static string Makers {
            get {
                return ResourceManager.GetString("Makers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркетинг.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа контент.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление разрешениями.
        /// </summary>
        internal static string Permission_management {
            get {
                return ResourceManager.GetString("Permission management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрины.
        /// </summary>
        internal static string Points_of_sale {
            get {
                return ResourceManager.GetString("Points of sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экземпляры.
        /// </summary>
        internal static string POS_content {
            get {
                return ResourceManager.GetString("POS content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промо акции.
        /// </summary>
        internal static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История меток.
        /// </summary>
        internal static string Tracking_history {
            get {
                return ResourceManager.GetString("Tracking history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка таблиц.
        /// </summary>
        internal static string Uploading_table {
            get {
                return ResourceManager.GetString("Uploading table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммуникации.
        /// </summary>
        internal static string UserNotifications {
            get {
                return ResourceManager.GetString("UserNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
