//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasladdinPlace.UI.Resources.Views.Checks {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _fiscalizationChecksPartial {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _fiscalizationChecksPartial() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NasladdinPlace.UI.Resources.Views.Checks._fiscalizationChecksPartial", typeof(_fiscalizationChecksPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Fiscalization_infos {
            get {
                return ResourceManager.GetString("Fiscalization infos", resourceCulture);
            }
        }
        
        public static string FiscalizationType {
            get {
                return ResourceManager.GetString("FiscalizationType", resourceCulture);
            }
        }
        
        public static string FiscalizationInfoTitle {
            get {
                return ResourceManager.GetString("FiscalizationInfoTitle", resourceCulture);
            }
        }
        
        public static string FiscalizationState {
            get {
                return ResourceManager.GetString("FiscalizationState", resourceCulture);
            }
        }
        
        public static string No_records {
            get {
                return ResourceManager.GetString("No records", resourceCulture);
            }
        }
        
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        public static string IncomeRefund {
            get {
                return ResourceManager.GetString("IncomeRefund", resourceCulture);
            }
        }
        
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        public static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
    }
}
