//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasladdinPlace.UI.Resources.Views.Checks {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NasladdinPlace.UI.Resources.Views.Checks.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Actual_Payment_Amount {
            get {
                return ResourceManager.GetString("Actual Payment Amount", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string Artical {
            get {
                return ResourceManager.GetString("Artical", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Bonuses {
            get {
                return ResourceManager.GetString("Bonuses", resourceCulture);
            }
        }
        
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        public static string Discount_in_bounuses {
            get {
                return ResourceManager.GetString("Discount in bounuses", resourceCulture);
            }
        }
        
        public static string Empty_table {
            get {
                return ResourceManager.GetString("Empty table", resourceCulture);
            }
        }
        
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        public static string Is_Inside {
            get {
                return ResourceManager.GetString("Is Inside", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string Hard_to_Detect {
            get {
                return ResourceManager.GetString("Hard to Detect", resourceCulture);
            }
        }
        
        public static string List_of_transactions {
            get {
                return ResourceManager.GetString("List of transactions", resourceCulture);
            }
        }
        
        public static string No_records {
            get {
                return ResourceManager.GetString("No records", resourceCulture);
            }
        }
        
        public static string Unverified {
            get {
                return ResourceManager.GetString("Unverified", resourceCulture);
            }
        }
        
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        public static string Operation_Status {
            get {
                return ResourceManager.GetString("Operation Status", resourceCulture);
            }
        }
        
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        public static string pc_ {
            get {
                return ResourceManager.GetString("pc.", resourceCulture);
            }
        }
        
        public static string PendingCompletion {
            get {
                return ResourceManager.GetString("PendingCompletion", resourceCulture);
            }
        }
        
        public static string PendingPayment {
            get {
                return ResourceManager.GetString("PendingPayment", resourceCulture);
            }
        }
        
        public static string Point_of_Sale {
            get {
                return ResourceManager.GetString("Point of Sale", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        public static string Refunded {
            get {
                return ResourceManager.GetString("Refunded", resourceCulture);
            }
        }
        
        public static string Total_cost {
            get {
                return ResourceManager.GetString("Total cost", resourceCulture);
            }
        }
        
        public static string Total_refund_bonus {
            get {
                return ResourceManager.GetString("Total refund bonus", resourceCulture);
            }
        }
        
        public static string Total_refund_money {
            get {
                return ResourceManager.GetString("Total refund money", resourceCulture);
            }
        }
        
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        public static string User_Information {
            get {
                return ResourceManager.GetString("User Information", resourceCulture);
            }
        }
        
        public static string Edit_details_check {
            get {
                return ResourceManager.GetString("Edit details check", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Panel_settings {
            get {
                return ResourceManager.GetString("Panel settings", resourceCulture);
            }
        }
        
        public static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        public static string Confirm_good {
            get {
                return ResourceManager.GetString("Confirm good", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Refund_good {
            get {
                return ResourceManager.GetString("Refund good", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string Additional_info {
            get {
                return ResourceManager.GetString("Additional info", resourceCulture);
            }
        }
        
        public static string Unexpectedly_found_date {
            get {
                return ResourceManager.GetString("Unexpectedly found date", resourceCulture);
            }
        }
        
        public static string Unexpectedly_lost_date {
            get {
                return ResourceManager.GetString("Unexpectedly lost date", resourceCulture);
            }
        }
        
        public static string Label_was_found {
            get {
                return ResourceManager.GetString("Label was found", resourceCulture);
            }
        }
        
        public static string Label_was_lost {
            get {
                return ResourceManager.GetString("Label was lost", resourceCulture);
            }
        }
        
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        public static string before_the_purchase {
            get {
                return ResourceManager.GetString("before the purchase", resourceCulture);
            }
        }
        
        public static string after_the_purchase {
            get {
                return ResourceManager.GetString("after the purchase", resourceCulture);
            }
        }
        
        public static string Will_be_deleted {
            get {
                return ResourceManager.GetString("Will be deleted", resourceCulture);
            }
        }
        
        public static string Will_be_paid {
            get {
                return ResourceManager.GetString("Will be paid", resourceCulture);
            }
        }
        
        public static string Will_be_refunded {
            get {
                return ResourceManager.GetString("Will be refunded", resourceCulture);
            }
        }
    }
}
