//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasladdinPlace.UI.Resources.Views.GoodsMoving {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetChecks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetChecks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NasladdinPlace.UI.Resources.Views.GoodsMoving.GetChecks", typeof(GetChecks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма к оплате.
        /// </summary>
        internal static string Actual_payment_amount {
            get {
                return ResourceManager.GetString("Actual payment amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все витрины.
        /// </summary>
        internal static string All_points_of_sale {
            get {
                return ResourceManager.GetString("All points of sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул.
        /// </summary>
        internal static string Artical {
            get {
                return ResourceManager.GetString("Artical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бонус.
        /// </summary>
        internal static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куплено.
        /// </summary>
        internal static string Bought_quantity {
            get {
                return ResourceManager.GetString("Bought quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка.
        /// </summary>
        internal static string BoughtGoods {
            get {
                return ResourceManager.GetString("BoughtGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чеки.
        /// </summary>
        internal static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершена.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домой.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купленные товары.
        /// </summary>
        internal static string LabeledGoods {
            get {
                return ResourceManager.GetString("LabeledGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без изменений.
        /// </summary>
        internal static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрано.
        /// </summary>
        internal static string Not_selected {
            get {
                return ResourceManager.GetString("Not selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыта.
        /// </summary>
        internal static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не завершена.
        /// </summary>
        internal static string Operation_is_not_completed {
            get {
                return ResourceManager.GetString("Operation is not completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип операции.
        /// </summary>
        internal static string Operation_type {
            get {
                return ResourceManager.GetString("Operation type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операций.
        /// </summary>
        internal static string Operations_quantity {
            get {
                return ResourceManager.GetString("Operations quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплачена.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает завершения.
        /// </summary>
        internal static string PendingCompletion {
            get {
                return ResourceManager.GetString("PendingCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает оплаты.
        /// </summary>
        internal static string PendingPayment {
            get {
                return ResourceManager.GetString("PendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Phone_number {
            get {
                return ResourceManager.GetString("Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрина.
        /// </summary>
        internal static string Point_of_sale {
            get {
                return ResourceManager.GetString("Point of sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрины.
        /// </summary>
        internal static string Points_of_sale {
            get {
                return ResourceManager.GetString("Points of sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущая.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string Purchase_amount {
            get {
                return ResourceManager.GetString("Purchase amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата покупки.
        /// </summary>
        internal static string Purchase_date {
            get {
                return ResourceManager.GetString("Purchase date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куплено.
        /// </summary>
        internal static string Purchase_quantity {
            get {
                return ResourceManager.GetString("Purchase quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положено.
        /// </summary>
        internal static string Put_quantity {
            get {
                return ResourceManager.GetString("Put quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string PutGoods {
            get {
                return ResourceManager.GetString("PutGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат.
        /// </summary>
        internal static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возвратить.
        /// </summary>
        internal static string Refund_payment {
            get {
                return ResourceManager.GetString("Refund payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возвращено.
        /// </summary>
        internal static string Refunded {
            get {
                return ResourceManager.GetString("Refunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск .
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус операции.
        /// </summary>
        internal static string Status_operation {
            get {
                return ResourceManager.GetString("Status operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взято.
        /// </summary>
        internal static string Taken_quantity {
            get {
                return ResourceManager.GetString("Taken quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка.
        /// </summary>
        internal static string TakenGoods {
            get {
                return ResourceManager.GetString("TakenGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        internal static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
