//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasladdinPlace.UI.Resources.Views.GoodsMoving {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NasladdinPlace.UI.Resources.Views.GoodsMoving.TransactionDetails", typeof(TransactionDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование чека.
        /// </summary>
        internal static string CheckEditing {
            get {
                return ResourceManager.GetString("CheckEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая информация.
        /// </summary>
        internal static string CommonInformaiton {
            get {
                return ResourceManager.GetString("CommonInformaiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фискализация.
        /// </summary>
        internal static string Fiscalization {
            get {
                return ResourceManager.GetString("Fiscalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Движение ТМЦ.
        /// </summary>
        internal static string GoodsMoving {
            get {
                return ResourceManager.GetString("GoodsMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домой.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали транзакции.
        /// </summary>
        internal static string PosOperationTransactionDetails {
            get {
                return ResourceManager.GetString("PosOperationTransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат.
        /// </summary>
        internal static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка.
        /// </summary>
        internal static string RegularPurchase {
            get {
                return ResourceManager.GetString("RegularPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
    }
}
