//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasladdinPlace.Core.Services.Authorization.AppFeatures.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NasladdinPlace.Core.Services.Authorization.AppFeatures.Resources.PermissionsResou" +
                            "rce", typeof(PermissionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление ролями (создание/редактирование/удаление ролей, настройка разрешений для ролей).
        /// </summary>
        public static string AclManagementPermission {
            get {
                return ResourceManager.GetString("AclManagementPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление логов витрин.
        /// </summary>
        public static string DeleteLogPermission {
            get {
                return ResourceManager.GetString("DeleteLogPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление витрины (в разрезе объектов/по праву доступа).
        /// </summary>
        public static string DeletePosPermission {
            get {
                return ResourceManager.GetString("DeletePosPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление скидками (создание/редактирование).
        /// </summary>
        public static string DiscountCrudPermission {
            get {
                return ResourceManager.GetString("DiscountCrudPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление движениями ТМЦ (редактирование чека; просмотр истории; добавление/удаление товара в чеке; возврат средств и т.д.).
        /// </summary>
        public static string DocumentGoodsMovingPermission {
            get {
                return ResourceManager.GetString("DocumentGoodsMovingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление товарами (создание/редактирование/удаление товара и медиа которое относится к нему).
        /// </summary>
        public static string GoodCrudPermission {
            get {
                return ResourceManager.GetString("GoodCrudPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление доступом к витрине.
        /// </summary>
        public static string GrantAccessToPosPermission {
            get {
                return ResourceManager.GetString("GrantAccessToPosPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификация товаров (управление дверьми, привязка/отвязка меток).
        /// </summary>
        public static string LabeledGoodManagementPermission {
            get {
                return ResourceManager.GetString("LabeledGoodManagementPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление производителями (создание/редактирование/удаление).
        /// </summary>
        public static string MakerCrudPermission {
            get {
                return ResourceManager.GetString("MakerCrudPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление витрины и редактирование настроек.
        /// </summary>
        public static string PosCrudPermission {
            get {
                return ResourceManager.GetString("PosCrudPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размещение товаров (управление дверьми).
        /// </summary>
        public static string PosDoorsManagementPermission {
            get {
                return ResourceManager.GetString("PosDoorsManagementPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживание витрин (мониторинг/управление состоянием).
        /// </summary>
        public static string PosMonitoringAndSupportPermission {
            get {
                return ResourceManager.GetString("PosMonitoringAndSupportPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление шаблонами главной страницы витрин (создание/редактирование).
        /// </summary>
        public static string PosScreenTemplateEditPermission {
            get {
                return ResourceManager.GetString("PosScreenTemplateEditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление версиями витрин.
        /// </summary>
        public static string PosVersionManagementPermission {
            get {
                return ResourceManager.GetString("PosVersionManagementPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление промоакциями.
        /// </summary>
        public static string PromotionSettingsPermission {
            get {
                return ResourceManager.GetString("PromotionSettingsPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к страницам портала без права действий.
        /// </summary>
        public static string ReadOnlyAccess {
            get {
                return ResourceManager.GetString("ReadOnlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление отчётами (добавление/редактирование/удаление).
        /// </summary>
        public static string ReportCrudPermission {
            get {
                return ResourceManager.GetString("ReportCrudPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к ежедневным отчетам.
        /// </summary>
        public static string ReportUploadingPermission {
            get {
                return ResourceManager.GetString("ReportUploadingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями (создание/редактирование пользователя/смена пароля).
        /// </summary>
        public static string UserManagementPermission {
            get {
                return ResourceManager.GetString("UserManagementPermission", resourceCulture);
            }
        }
    }
}
