export const LOAD_UNTIED_LABELED_GOODS_SUCCESS =
  'LOAD_UNTIED_LABELED_GOODS_SUCCESS';
export const LOAD_UNTIED_LABELED_GOODS_FAILURE =
  'LOAD_UNTIED_LABELED_GOODS_FAILURE';
export const LOAD_UNTIED_LABELED_GOODS = 'LOAD_UNTIED_LABELED_GOODS';
export const PERFORM_OPERATION_WITH_LABELED_GOODS_SUCCESS =
  'PERFORM_OPERATION_WITH_LABELED_GOODS_SUCCESS';
export const TIE_LABELS_TO_GOOD = 'TIE_LABELS_TO_GOOD';
export const BLOCK_LABELED_GOODS = 'BLOCK_LABELED_GOODS';
export const OPEN_LEFT_DOOR = 'OPEN_LEFT_DOOR';
export const OPEN_RIGHT_DOOR = 'OPEN_RIGHT_DOOR';
export const CLOSE_DOORS = 'CLOSE_DOORS';
export const REQUEST_CONTENT = 'REQUEST_CONTENT';
