export const LOAD_POS_REAL_TIME_INFO = 'LOAD_POS_REAL_TIME_INFO';
export const LOAD_POS_REAL_TIME_INFO_SUCCESS =
  'LOAD_POS_REAL_TIME_INFO_SUCCESS';
export const LOAD_POS_REAL_TIME_INFO_FAILURE =
  'LOAD_POINTS_OF_SALE_REAL_TIME_INFO_FAILURE';
