// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NasladdinPlace.DAL;

namespace NasladdinPlace.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191231042941_InsertUnpaidCheckPaymentConfiguration")]
    partial class InsertUnpaidCheckPaymentConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("ProviderKey");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("ProviderKey", "LoginProvider");

                    b.HasAlternateKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("UserId");

                    b.HasAlternateKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AllowedPosMode", b =>
                {
                    b.Property<int>("PosId");

                    b.Property<int>("Mode");

                    b.HasKey("PosId", "Mode");

                    b.ToTable("AllowedPosModes");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AppFeatureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("PermissionCategory");

                    b.HasKey("Id");

                    b.ToTable("AppFeatureItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AppFeatureItemsToRole", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("AppFeatureItemId");

                    b.HasKey("RoleId", "AppFeatureItemId");

                    b.HasIndex("AppFeatureItemId");

                    b.ToTable("AppFeatureItemsToRoles");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<int?>("ActivePaymentCardId");

                    b.Property<int?>("Activity");

                    b.Property<int?>("Age");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("ChangePhoneNumberTokenRemainder")
                        .HasMaxLength(10);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(255);

                    b.Property<int>("Gender");

                    b.Property<int?>("Goal");

                    b.Property<int?>("Height");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<DateTime?>("PaymentCardVerificationCompletionDate");

                    b.Property<DateTime?>("PaymentCardVerificationInitiationDate");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int?>("Pregnancy");

                    b.Property<DateTime?>("RegistrationCompletionDate");

                    b.Property<DateTime>("RegistrationInitiationDate");

                    b.Property<string>("SecurityStamp");

                    b.Property<decimal>("TotalBonusPoints");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int?>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ActivePaymentCardId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.BankTransactionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("BankTransactionId");

                    b.Property<string>("Comment")
                        .HasMaxLength(3000);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("PaymentCardId");

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCardId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("BankTransactionInfos");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.BankTransactionInfoVersionTwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("BankTransactionId");

                    b.Property<string>("Comment")
                        .HasMaxLength(3000);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("PaymentCardId");

                    b.Property<int>("PosOperationTransactionId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCardId");

                    b.HasIndex("PosOperationTransactionId");

                    b.ToTable("BankTransactionInfosVersionTwo");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("GoodId");

                    b.Property<bool>("IsModifiedByAdmin");

                    b.Property<int>("LabeledGoodId");

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<decimal>("Price");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("GoodId");

                    b.HasIndex("LabeledGoodId");

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("CheckItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItemAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CheckItemId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("EditorId");

                    b.Property<int>("NewStatus");

                    b.Property<int>("OldStatus");

                    b.HasKey("Id");

                    b.HasIndex("CheckItemId");

                    b.HasIndex("EditorId");

                    b.ToTable("CheckItemsAuditHistory");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationKey", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("ParentId");

                    b.Property<int>("ValueDataType");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ConfigurationKeys");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KeyId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.ToTable("ConfigurationValues");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasDefaultValue("RUB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasAlternateKey("IsoCode");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<int>("DiscountArea");

                    b.Property<decimal>("DiscountInPercentage");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountId");

                    b.Property<int>("RuleArea");

                    b.Property<int>("RuleType");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("DiscountRules");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRuleValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountRuleId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("ValueType");

                    b.HasKey("Id");

                    b.HasIndex("DiscountRuleId");

                    b.ToTable("DiscountRuleValues");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.PosDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountId");

                    b.Property<int>("PosId");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("PosId");

                    b.ToTable("PosDiscounts");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMoving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DocumentNumber");

                    b.Property<Guid?>("ErpId");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPosted");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("DocumentsGoodsMoving");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMovingLabeledGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BalanceType");

                    b.Property<int>("DocumentTableItemId");

                    b.Property<int>("LabeledGoodId");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTableItemId");

                    b.HasIndex("LabeledGoodId");

                    b.ToTable("DocumentGoodsMovingLabeledGoods");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMovingTableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BalanceAtBegining");

                    b.Property<int>("BalanceAtEnd");

                    b.Property<int>("DocumentId");

                    b.Property<int?>("GoodId");

                    b.Property<int>("Income");

                    b.Property<string>("LabelsAtBegining");

                    b.Property<string>("LabelsAtEnd");

                    b.Property<int>("LineNum");

                    b.Property<int>("Outcome");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("GoodId");

                    b.ToTable("DocumentGoodsMovingTableItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Fiscalization.FiscalizationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("CorrectionAmount");

                    b.Property<DateTime>("DateTimeRequest");

                    b.Property<DateTime?>("DateTimeResponse");

                    b.Property<DateTime?>("DocumentDateTime");

                    b.Property<string>("DocumentInfo")
                        .HasMaxLength(3000);

                    b.Property<string>("ErrorInfo")
                        .HasMaxLength(3000);

                    b.Property<string>("FiscalizationNumber")
                        .HasMaxLength(50);

                    b.Property<string>("FiscalizationSerial")
                        .HasMaxLength(50);

                    b.Property<string>("FiscalizationSign")
                        .HasMaxLength(50);

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<string>("QrCodeValue")
                        .HasMaxLength(150);

                    b.Property<Guid>("RequestId");

                    b.Property<int>("State")
                        .IsConcurrencyToken();

                    b.Property<decimal?>("TotalFiscalizationAmount");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("FiscalizationInfos");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Fiscalization.FiscalizationInfoVersionTwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("CorrectionAmount");

                    b.Property<DateTime?>("DocumentDateTime");

                    b.Property<string>("DocumentInfo")
                        .HasMaxLength(3000);

                    b.Property<string>("ErrorInfo")
                        .HasMaxLength(3000);

                    b.Property<string>("FiscalizationNumber")
                        .HasMaxLength(50);

                    b.Property<string>("FiscalizationSerial")
                        .HasMaxLength(50);

                    b.Property<string>("FiscalizationSign")
                        .HasMaxLength(50);

                    b.Property<int>("PosOperationTransactionId");

                    b.Property<string>("QrCodeValue")
                        .HasMaxLength(150);

                    b.Property<DateTime>("RequestDateTime");

                    b.Property<Guid>("RequestId");

                    b.Property<DateTime?>("ResponseDateTime");

                    b.Property<int>("State")
                        .IsConcurrencyToken();

                    b.Property<decimal?>("TotalFiscalizationAmount");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PosOperationTransactionId");

                    b.ToTable("FiscalizationInfosVersionTwo");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.FiscalizationCheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("CheckItemId");

                    b.Property<int>("FiscalizationInfoId");

                    b.HasKey("Id");

                    b.HasIndex("CheckItemId");

                    b.HasIndex("FiscalizationInfoId");

                    b.ToTable("FiscalizationCheckItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Composition");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int>("GoodCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("MakerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<double?>("NetWeight");

                    b.Property<double?>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("GoodCategoryId");

                    b.HasIndex("MakerId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.GoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("GoodCategories");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.GoodImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GoodId");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.ToTable("GoodImages");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.ProteinsFatsCarbohydratesCalories", b =>
                {
                    b.Property<int>("Id");

                    b.Property<double>("CaloriesInKcal");

                    b.Property<double>("CarbohydratesInGrams");

                    b.Property<double>("FatsInGrams");

                    b.Property<double>("ProteinsInGrams");

                    b.HasKey("Id");

                    b.ToTable("ProteinsFatsCarbohydratesCalories");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrencyId");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<DateTime?>("FoundDateTime");

                    b.Property<int?>("GoodId");

                    b.Property<bool>("IsDisabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LostDateTime");

                    b.Property<DateTime?>("ManufactureDate");

                    b.Property<int?>("PosId");

                    b.Property<int?>("PosOperationId");

                    b.Property<decimal?>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("GoodId");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("LabeledGoods");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGoodTrackingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LabeledGoodId");

                    b.Property<int>("PosId");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("LabeledGoodId");

                    b.HasIndex("PosId");

                    b.ToTable("LabeledGoodsTrackingHistory");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Maker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("Makers");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MediaContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContentType");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasMaxLength(26214400);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UploadDateTime");

                    b.HasKey("Id");

                    b.ToTable("MediaContents");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MediaContentToPosPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<int>("MediaContentId");

                    b.Property<int>("PosScreenType");

                    b.HasKey("Id");

                    b.HasIndex("MediaContentId");

                    b.ToTable("MediaContentToPosPlatforms");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MessengerContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("MessengerContacts");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CryptogramSource");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("FirstSixDigits")
                        .HasMaxLength(6);

                    b.Property<string>("LastFourDigits")
                        .HasMaxLength(4);

                    b.Property<int>("PaymentSystem");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentCards");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PointsOfSaleToRole", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("PosId");

                    b.HasKey("RoleId", "PosId");

                    b.HasIndex("PosId");

                    b.ToTable("PointsOfSaleToRoles");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Pos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbbreviatedName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("AccurateLocation");

                    b.Property<bool>("AreNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int>("CityId");

                    b.Property<bool>("IsRestrictedAccess")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("PosScreenTemplateId");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasDefaultValue("8081c0fc-a73e-4397-a282-8e0a2c351330");

                    b.Property<int>("QrCodeGenerationType");

                    b.Property<int?>("RequiredScreenResolutionHeight");

                    b.Property<int?>("RequiredScreenResolutionWidth");

                    b.Property<DateTime>("ScreenTemplateAppliedDate");

                    b.Property<int>("SensorControllerType");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("UseNewPaymentSystem")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PosScreenTemplateId");

                    b.ToTable("PointsOfSale");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosAbnormalSensorMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateMeasured");

                    b.Property<int>("MeasurementUnit");

                    b.Property<double>("MeasurementValue")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0.0);

                    b.Property<int>("PosId");

                    b.Property<int>("SensorPosition");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosAbnormalSensorMeasurements");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosDoorsState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("PosId");

                    b.Property<int?>("PosOperationId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("PosDoorsStates");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("PosId");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosImages");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasMaxLength(26214400);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("LogType");

                    b.Property<int>("PosId");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosLogs");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosMediaContent", b =>
                {
                    b.Property<int>("PosId");

                    b.Property<int>("MediaContentId");

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<int>("PosScreenType");

                    b.HasKey("PosId", "MediaContentId");

                    b.HasIndex("MediaContentId");

                    b.ToTable("PosMediaContents");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PosId");

                    b.Property<DateTime?>("AuditCompletionDateTime");

                    b.Property<DateTime?>("AuditRequestDateTime");

                    b.Property<decimal>("BonusAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("Brand");

                    b.Property<DateTime?>("CompletionInitiationDate");

                    b.Property<int>("CorrectnessStatus");

                    b.Property<DateTime?>("DateCompleted");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<DateTime>("DateStarted");

                    b.Property<int>("Mode");

                    b.Property<int>("Status")
                        .IsConcurrencyToken();

                    b.Property<int>("UserId");

                    b.HasKey("Id", "PosId");

                    b.HasIndex("PosId");

                    b.HasIndex("UserId");

                    b.ToTable("PosOperations");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperationTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BankTransactionPaidDate");

                    b.Property<decimal>("BonusAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("FiscalizationAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("FiscalizationDate");

                    b.Property<int?>("LastBankTransactionInfoId");

                    b.Property<int?>("LastFiscalizationInfoId");

                    b.Property<decimal>("MoneyAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<int>("Status")
                        .IsConcurrencyToken();

                    b.Property<decimal>("TotalCost");

                    b.Property<decimal>("TotalDiscountAmount");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("LastBankTransactionInfoId");

                    b.HasIndex("LastFiscalizationInfoId");

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("PosOperationTransactions");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperationTransactionCheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("CheckItemId");

                    b.Property<decimal>("CostInBonusPoints");

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("DiscountAmount");

                    b.Property<int>("PosOperationTransactionId");

                    b.HasKey("Id");

                    b.HasIndex("CheckItemId");

                    b.HasIndex("PosOperationTransactionId");

                    b.ToTable("PosOperationTransactionCheckItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosScreenTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("PosScreenTemplates");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("PosId");

                    b.Property<double>("Temperature");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosTemperatures");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PromotionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("NotificationType");

                    b.Property<byte>("PromotionType");

                    b.Property<DateTime>("SendMessageDateTime");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PromotionLogs");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PromotionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BonusValue");

                    b.Property<bool>("IsEnabled");

                    b.Property<bool>("IsNotificationEnabled");

                    b.Property<TimeSpan>("NotificationStartTime");

                    b.Property<byte>("PromotionType");

                    b.HasKey("Id");

                    b.HasIndex("PromotionType")
                        .IsUnique();

                    b.ToTable("PromotionSettings");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.ReportUploadingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatchSize");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Sheet")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("ReportsUploadingInfo");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.RolePermittedAppFeature", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("AppFeature");

                    b.HasKey("RoleId", "AppFeature");

                    b.HasIndex("AppFeature");

                    b.ToTable("RolesPermittedAppFeatures");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserBonusPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AvailableBonusPoints");

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("PosOperationTransactionId");

                    b.Property<int>("Type");

                    b.Property<int>("UserId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("PosOperationTransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersBonusPoints");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserFirebaseToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Brand");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Brand")
                        .IsUnique();

                    b.ToTable("UserFirebaseTokens");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeSent");

                    b.Property<string>("MessageText")
                        .IsRequired();

                    b.Property<byte>("NotificationArea");

                    b.Property<byte>("NotificationType");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PushNotificationToken");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("RoleId", "UserId");

                    b.HasAlternateKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("NasladdinPlace.DAL.Entities.FeedbackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("DeviceOperatingSystem")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("PosId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ClientSecret");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("ConsentType");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Permissions");

                    b.Property<string>("PostLogoutRedirectUris");

                    b.Property<string>("Properties");

                    b.Property<string>("RedirectUris");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("Properties");

                    b.Property<string>("Scopes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictScope<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Properties");

                    b.Property<string>("Resources");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictToken<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationId");

                    b.Property<int?>("AuthorizationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset?>("CreationDate");

                    b.Property<DateTimeOffset?>("ExpirationDate");

                    b.Property<string>("Payload");

                    b.Property<string>("Properties");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AllowedPosMode", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos")
                        .WithMany("InternalAllowedModes")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AppFeatureItemsToRole", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.AppFeatureItem")
                        .WithMany("RolePermittedFeatures")
                        .HasForeignKey("AppFeatureItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany("InternalPermittedFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.ApplicationUser", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PaymentCard", "ActivePaymentCard")
                        .WithMany()
                        .HasForeignKey("ActivePaymentCardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.BankTransactionInfo", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PaymentCard", "PaymentCard")
                        .WithMany()
                        .HasForeignKey("PaymentCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation")
                        .WithMany("BankTransactionInfos")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.BankTransactionInfoVersionTwo", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PaymentCard", "PaymentCard")
                        .WithMany()
                        .HasForeignKey("PaymentCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperationTransaction", "PosOperationTransaction")
                        .WithMany("BankTransactionInfos")
                        .HasForeignKey("PosOperationTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItem", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Goods.Good", "Good")
                        .WithMany("CheckItems")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.LabeledGood", "LabeledGood")
                        .WithMany()
                        .HasForeignKey("LabeledGoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("CheckItems")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItemAuditRecord", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.CheckItem", "CheckItem")
                        .WithMany("AuditRecords")
                        .HasForeignKey("CheckItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("CheckItemsAuditHistory")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.City", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationKey", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Configuration.ConfigurationKey")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationValue", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Configuration.ConfigurationKey")
                        .WithMany("Values")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRule", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Discounts.Discount", "Discount")
                        .WithMany("DiscountRules")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRuleValue", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Discounts.DiscountRule", "DiscountRule")
                        .WithMany("DiscountRuleValues")
                        .HasForeignKey("DiscountRuleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.PosDiscount", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Discounts.Discount", "Discount")
                        .WithMany("PosDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMoving", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "PointOfSale")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("DocumentsGoodsMoving")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMovingLabeledGood", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMovingTableItem", "DocumentGoodsMovingTableItem")
                        .WithMany()
                        .HasForeignKey("DocumentTableItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.LabeledGood", "LabeledGood")
                        .WithMany()
                        .HasForeignKey("LabeledGoodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMovingTableItem", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Documents.GoodsMoving.DocumentGoodsMoving", "Document")
                        .WithMany("TablePart")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Goods.Good", "Good")
                        .WithMany()
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Fiscalization.FiscalizationInfo", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("FiscalizationInfos")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Fiscalization.FiscalizationInfoVersionTwo", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PosOperationTransaction", "PosOperationTransaction")
                        .WithMany("FiscalizationInfos")
                        .HasForeignKey("PosOperationTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.FiscalizationCheckItem", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.CheckItem", "CheckItem")
                        .WithMany("FiscalizationCheckItems")
                        .HasForeignKey("CheckItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Fiscalization.FiscalizationInfo", "FiscalizationInfo")
                        .WithMany("FiscalizationCheckItems")
                        .HasForeignKey("FiscalizationInfoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.Good", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Goods.GoodCategory", "GoodCategory")
                        .WithMany("Goods")
                        .HasForeignKey("GoodCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Maker", "Maker")
                        .WithMany()
                        .HasForeignKey("MakerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.GoodImage", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Goods.Good", "Good")
                        .WithMany("GoodImages")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Goods.ProteinsFatsCarbohydratesCalories", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Goods.Good")
                        .WithOne("ProteinsFatsCarbohydratesCalories")
                        .HasForeignKey("NasladdinPlace.Core.Models.Goods.ProteinsFatsCarbohydratesCalories", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGood", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Goods.Good", "Good")
                        .WithMany("LabeledGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("LabeledGoods")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("LabeledGoods")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGoodTrackingRecord", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.LabeledGood", "LabeledGood")
                        .WithMany("TrackingRecords")
                        .HasForeignKey("LabeledGoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MediaContentToPosPlatform", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.MediaContent", "MediaContent")
                        .WithMany()
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PaymentCard", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("PaymentCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PointsOfSaleToRole", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos")
                        .WithMany("AssignedRoles")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany("InternalAssignedPoses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Pos", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosScreenTemplate", "PosScreenTemplate")
                        .WithMany("PointsOfSale")
                        .HasForeignKey("PosScreenTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosAbnormalSensorMeasurement", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("PosAbnormalSensorMeasurements")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosDoorsState", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("PosDoorsStates")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosImage", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("Images")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosLog", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosMediaContent", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.MediaContent", "MediaContent")
                        .WithMany()
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperation", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("Operations")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("PosOperations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperationTransaction", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.BankTransactionInfoVersionTwo", "LastBankTransactionInfo")
                        .WithMany()
                        .HasForeignKey("LastBankTransactionInfoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Fiscalization.FiscalizationInfoVersionTwo", "LastFiscalizationInfo")
                        .WithMany()
                        .HasForeignKey("LastFiscalizationInfoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("PosOperationTransactions")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperationTransactionCheckItem", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.CheckItem", "CheckItem")
                        .WithMany("PosOperationTransactionCheckItems")
                        .HasForeignKey("CheckItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperationTransaction", "PosOperationTransaction")
                        .WithMany("PosOperationTransactionCheckItems")
                        .HasForeignKey("PosOperationTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosTemperature", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PromotionLog", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("PromotionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.RolePermittedAppFeature", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany("InternalPermittedAppFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserBonusPoint", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PosOperationTransaction", "PosOperationTransaction")
                        .WithMany("BonusPoints")
                        .HasForeignKey("PosOperationTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("BonusPoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserFirebaseToken", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany("FirebaseTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserNotification", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserRole", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.DAL.Entities.FeedbackEntity", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization<int>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication<int>", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictToken<int>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication<int>", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization<int>", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
