// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NasladdinPlace.DAL;

namespace NasladdinPlace.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190607063204_ChangePosOperationDateSentForVerificationToCompletionInitiationDate")]
    partial class ChangePosOperationDateSentForVerificationToCompletionInitiationDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("ProviderKey");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("ProviderKey", "LoginProvider");

                    b.HasAlternateKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("RoleId", "UserId");

                    b.HasAlternateKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("UserId");

                    b.HasAlternateKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AllowedPosMode", b =>
                {
                    b.Property<int>("PosId");

                    b.Property<int>("Mode");

                    b.HasKey("PosId", "Mode");

                    b.ToTable("AllowedPosModes");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<int?>("ActivePaymentCardId");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("ChangePhoneNumberTokenRemainder")
                        .HasMaxLength(10);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(255);

                    b.Property<int>("Gender");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<DateTime?>("PaymentCardVerificationCompletionDate");

                    b.Property<DateTime?>("PaymentCardVerificationInitiationDate");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<DateTime?>("RegistrationCompletionDate");

                    b.Property<DateTime>("RegistrationInitiationDate");

                    b.Property<string>("SecurityStamp");

                    b.Property<decimal>("TotalBonus");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ActivePaymentCardId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.BankTransactionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("BankTransactionId");

                    b.Property<string>("Comment")
                        .HasMaxLength(3000);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("PaymentCardId");

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCardId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("BankTransactionInfos");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("GoodId");

                    b.Property<bool>("IsModifiedByAdmin");

                    b.Property<int>("LabeledGoodId");

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<decimal>("Price");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("GoodId");

                    b.HasIndex("LabeledGoodId");

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("CheckItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItemAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CheckItemId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("EditorId");

                    b.Property<int>("NewStatus");

                    b.Property<int>("OldStatus");

                    b.HasKey("Id");

                    b.HasIndex("CheckItemId");

                    b.HasIndex("EditorId");

                    b.ToTable("CheckItemsAuditHistory");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationKey", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("ParentId");

                    b.Property<int>("ValueDataType");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ConfigurationKeys");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KeyId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.ToTable("ConfigurationValues");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasDefaultValue("RUB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasAlternateKey("IsoCode");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<int>("DiscountArea");

                    b.Property<decimal>("DiscountInPercentage");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountId");

                    b.Property<int>("RuleArea");

                    b.Property<int>("RuleType");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("DiscountRules");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRuleValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountRuleId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("ValueType");

                    b.HasKey("Id");

                    b.HasIndex("DiscountRuleId");

                    b.ToTable("DiscountRuleValues");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.PosDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountId");

                    b.Property<int>("PosId");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("PosId");

                    b.ToTable("PosDiscounts");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.DriverLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("PosId");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("DriverLogs");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.FiscalizationCheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("CheckItemId");

                    b.Property<int>("FiscalizationInfoId");

                    b.HasKey("Id");

                    b.HasIndex("CheckItemId");

                    b.HasIndex("FiscalizationInfoId");

                    b.ToTable("FiscalizationCheckItems");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.FiscalizationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("CorrectionAmount");

                    b.Property<DateTime>("DateTimeRequest");

                    b.Property<DateTime?>("DateTimeResponse");

                    b.Property<DateTime?>("DocumentDateTime");

                    b.Property<string>("DocumentInfo")
                        .HasMaxLength(2000);

                    b.Property<string>("ErrorInfo")
                        .HasMaxLength(2000);

                    b.Property<string>("FiscalizationNumber")
                        .HasMaxLength(50);

                    b.Property<string>("FiscalizationSerial")
                        .HasMaxLength(50);

                    b.Property<string>("FiscalizationSign")
                        .HasMaxLength(50);

                    b.Property<int>("PosId");

                    b.Property<int>("PosOperationId");

                    b.Property<string>("QrCodeData")
                        .HasMaxLength(100000);

                    b.Property<string>("QrCodeFormat")
                        .HasMaxLength(10);

                    b.Property<Guid>("RequestId");

                    b.Property<int>("State")
                        .IsConcurrencyToken();

                    b.Property<decimal?>("TotalFiscalizationAmount");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("FiscalizationInfos");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int>("GoodCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("MakerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<double?>("NetWeight");

                    b.Property<double?>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("GoodCategoryId");

                    b.HasIndex("MakerId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.GoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("GoodCategories");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.GoodImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GoodId");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.ToTable("GoodImages");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrencyId");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<DateTime?>("FoundDateTime");

                    b.Property<int?>("GoodId");

                    b.Property<bool>("IsDisabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LostDateTime");

                    b.Property<DateTime?>("ManufactureDate");

                    b.Property<int?>("PosId");

                    b.Property<int?>("PosOperationId");

                    b.Property<decimal?>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("GoodId");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.HasIndex("PosId");

                    b.HasIndex("PosOperationId", "PosId");

                    b.ToTable("LabeledGoods");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGoodTrackingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LabeledGoodId");

                    b.Property<int>("PosId");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("LabeledGoodId");

                    b.HasIndex("PosId");

                    b.ToTable("LabeledGoodsTrackingHistory");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Maker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("Makers");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MediaContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContentType");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasMaxLength(26214400);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UploadDateTime");

                    b.HasKey("Id");

                    b.ToTable("MediaContents");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MediaContentToPosPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<int>("MediaContentId");

                    b.Property<int>("PosScreenType");

                    b.HasKey("Id");

                    b.HasIndex("MediaContentId");

                    b.ToTable("MediaContentToPosPlatforms");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CryptogramSource");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("FirstSixDigits")
                        .HasMaxLength(6);

                    b.Property<string>("LastFourDigits")
                        .HasMaxLength(4);

                    b.Property<int>("PaymentSystem");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentCards");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Pos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbbreviatedName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("AreNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int>("CityId");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasDefaultValue("8081c0fc-a73e-4397-a282-8e0a2c351330");

                    b.Property<int?>("RequiredScreenResolutionHeight");

                    b.Property<int?>("RequiredScreenResolutionWidth");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("UseLegacySensorsPosition");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfSale");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosAbnormalSensorMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateMeasured");

                    b.Property<int>("MeasurementUnit");

                    b.Property<double>("MeasurementValue")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0.0);

                    b.Property<int>("PosId");

                    b.Property<int>("SensorPosition");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosAbnormalSensorMeasurements");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("PosId");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosImages");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasMaxLength(26214400);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("LogType");

                    b.Property<int>("PosId");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.ToTable("PosLogs");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosMediaContent", b =>
                {
                    b.Property<int>("PosId");

                    b.Property<int>("MediaContentId");

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<int>("PosScreenType");

                    b.HasKey("PosId", "MediaContentId");

                    b.HasIndex("MediaContentId");

                    b.ToTable("PosMediaContents");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PosId");

                    b.Property<DateTime?>("AuditCompletionDateTime");

                    b.Property<DateTime?>("AuditRequestDateTime");

                    b.Property<decimal>("BonusAmount")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0m);

                    b.Property<int>("Brand");

                    b.Property<DateTime?>("CompletionInitiationDate");

                    b.Property<int>("CorrectnessStatus");

                    b.Property<DateTime?>("DateCompleted");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<DateTime>("DateStarted");

                    b.Property<int>("Mode");

                    b.Property<int>("Status")
                        .IsConcurrencyToken();

                    b.Property<int>("UserId");

                    b.HasKey("Id", "PosId");

                    b.HasIndex("PosId");

                    b.HasIndex("UserId");

                    b.ToTable("PosOperations");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PromotionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("NotificationType");

                    b.Property<byte>("PromotionType");

                    b.Property<DateTime>("SendMessageDateTime");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PromotionLogs");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PromotionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BonusValue");

                    b.Property<bool>("IsEnabled");

                    b.Property<bool>("IsNotificationEnabled");

                    b.Property<TimeSpan>("NotificationStartTime");

                    b.Property<byte>("PromotionType");

                    b.HasKey("Id");

                    b.HasIndex("PromotionType")
                        .IsUnique();

                    b.ToTable("PromotionSettings");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.ReportUploadingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Sheet")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("ReportsUploadingInfo");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.RolePermittedAppFeature", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("AppFeature");

                    b.HasKey("RoleId", "AppFeature");

                    b.HasIndex("AppFeature");

                    b.ToTable("RolesPermittedAppFeatures");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("Type");

                    b.Property<int>("UserId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersBonuses");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserFirebaseToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Brand");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Brand")
                        .IsUnique();

                    b.ToTable("UserFirebaseTokens");
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeSent");

                    b.Property<string>("MessageText");

                    b.Property<byte>("NotificationArea");

                    b.Property<byte>("NotificationType");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PushNotificationToken");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("NasladdinPlace.DAL.Entities.FeedbackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("DeviceOperatingSystem")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("PosId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PosId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ClientSecret");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("ConsentType");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Permissions");

                    b.Property<string>("PostLogoutRedirectUris");

                    b.Property<string>("Properties");

                    b.Property<string>("RedirectUris");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("Properties");

                    b.Property<string>("Scopes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictScope<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Properties");

                    b.Property<string>("Resources");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictToken<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationId");

                    b.Property<int?>("AuthorizationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset?>("CreationDate");

                    b.Property<DateTimeOffset?>("ExpirationDate");

                    b.Property<string>("Payload");

                    b.Property<string>("Properties");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.AllowedPosMode", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos")
                        .WithMany("InternalAllowedModes")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.ApplicationUser", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PaymentCard", "ActivePaymentCard")
                        .WithMany()
                        .HasForeignKey("ActivePaymentCardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.BankTransactionInfo", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PaymentCard", "PaymentCard")
                        .WithMany()
                        .HasForeignKey("PaymentCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation")
                        .WithMany("BankTransactionInfos")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItem", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Good", "Good")
                        .WithMany("CheckItems")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.LabeledGood", "LabeledGood")
                        .WithMany()
                        .HasForeignKey("LabeledGoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("CheckItems")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.CheckItemAuditRecord", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.CheckItem", "CheckItem")
                        .WithMany("AuditRecords")
                        .HasForeignKey("CheckItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("CheckItemsAuditHistory")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.City", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationKey", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Configuration.ConfigurationKey")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Configuration.ConfigurationValue", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Configuration.ConfigurationKey")
                        .WithMany("Values")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRule", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Discounts.Discount", "Discount")
                        .WithMany("DiscountRules")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.DiscountRuleValue", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Discounts.DiscountRule", "DiscountRule")
                        .WithMany("DiscountRuleValues")
                        .HasForeignKey("DiscountRuleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Discounts.PosDiscount", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Discounts.Discount", "Discount")
                        .WithMany("PosDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.FiscalizationCheckItem", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.CheckItem", "CheckItem")
                        .WithMany("FiscalizationCheckItems")
                        .HasForeignKey("CheckItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.FiscalizationInfo", "FiscalizationInfo")
                        .WithMany("FiscalizationCheckItems")
                        .HasForeignKey("FiscalizationInfoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.FiscalizationInfo", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("FiscalizationInfos")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Good", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.GoodCategory", "GoodCategory")
                        .WithMany("Goods")
                        .HasForeignKey("GoodCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Maker", "Maker")
                        .WithMany()
                        .HasForeignKey("MakerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.GoodImage", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Good", "Good")
                        .WithMany("GoodImages")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGood", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Good", "Good")
                        .WithMany("LabeledGoods")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("LabeledGoods")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.PosOperation", "PosOperation")
                        .WithMany("LabeledGoods")
                        .HasForeignKey("PosOperationId", "PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.LabeledGoodTrackingRecord", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.LabeledGood", "LabeledGood")
                        .WithMany("TrackingRecords")
                        .HasForeignKey("LabeledGoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.MediaContentToPosPlatform", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.MediaContent", "MediaContent")
                        .WithMany()
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PaymentCard", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("PaymentCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.Pos", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosAbnormalSensorMeasurement", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("PosAbnormalSensorMeasurements")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosImage", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("Images")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosLog", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosMediaContent", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.MediaContent", "MediaContent")
                        .WithMany()
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PosOperation", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany("Operations")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("PosOperations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.PromotionLog", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("PromotionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.RolePermittedAppFeature", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Role")
                        .WithMany("InternalPermittedAppFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserBonus", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany("UserBonuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserFirebaseToken", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser")
                        .WithMany("FirebaseTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.Core.Models.UserNotification", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NasladdinPlace.DAL.Entities.FeedbackEntity", b =>
                {
                    b.HasOne("NasladdinPlace.Core.Models.Pos", "Pos")
                        .WithMany()
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasladdinPlace.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization<int>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication<int>", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictToken<int>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication<int>", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization<int>", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
